export const EQUIPOS_FPC: string[] = [
    'América de Cali',
    'Atlético Bucaramanga',
    'Atlético Huila',
    'Atlético Nacional',
    'Águilas Doradas',
    'Alianza FC',
    'Boyacá Chicó',
    'Cúcuta Deportivo',
    'Deportes Quindío',
    'Deportes Tolima',
    'Deportivo Cali',
    'Deportivo Pasto',
    'Deportivo Pereira',
    'Envigado FC',
    'Fortaleza CEIF',
    'Independiente Medellín',
    'Independiente Santa Fe',
    'Internacional de Palmira',
    'Jaguares de Córdoba',
    'Llaneros FC',
    'La Equidad',
    'Leones FC',
    'Millonarios',
    'Orsomarso SC',
    'Patriotas Boyacá',
    'Real Cartagena',
    'Real Santander',
    'Tigres FC',
    'Unión Magdalena',
    'Valledupar FC'
  ];
  